apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change_form.html", success_url=reverse_lazy('accounts:password_change_done')), name='change_password'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"), name='password_change_done'),
    path('account-activation-sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('account-activated/', views.account_activated, name='account_activated'),
    path('account-activation-failed/', views.activation_failed, name='account_activation_failed')
]

apps/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.TasksListView.as_view(), name='tasks'),
    path('<uuid:pk>/', views.TaskDetailView.as_view(), name='task'),
    path('add-task/', views.TaskCreateView.as_view(), name='add_task'),
    path('<uuid:pk>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('<uuid:pk>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
    path('send-reminders/', views.send_reminders, name='send_reminders')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('', include('apps.tasks.urls'))
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    username = models.CharField(max_length=50, blank=True)
    email = models.EmailField(unique=True)
    is_verified = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.email
    
    def set_username(self):
        if self.username == "":
            self.username = self.email.split("@")[0]

    def save(self, *args, **kwargs):
        self.set_username()
        super(User, self).save(*args, **kwargs)

apps/accounts/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'email'
            ]

apps/accounts/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth import login

from .tokens import account_activation_token
from .models import User
from .forms import SignUpForm


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate account'
            message = render_to_string('accounts/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('accounts:account_activation_sent')

    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

def account_activation_sent(request):
    return render(request, 'accounts/account_activation_sent.html')

def account_activated(request):
    return render(request, 'accounts/account_activated.html')

def activation_failed(request):
    return render(request, 'accounts/account_activation_failed.html')

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_verified = True
        user.save()
        login(request, user)
        return redirect('accounts:account_activated')

    else:
        return render(request, 'account_activation_failed.html')
    

templates/accounts/account_activated.html
{% extends "base.html" %}

{% block content %}
  
<h1>Account activated!</h1>
<a href="{% url 'tasks:tasks' %}">Go to Main Page</a>

{% endblock %}

templates/accounts/account_activation_email.html
{% autoescape off %}
Hi {{ user.email }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/account_activation_failed.html
{% extends "base.html" %}

{% block content %}
  
<h1>Activation failed!</h1>

{% endblock %}

templates/accounts/account_activation_sent.html
{% extends "base.html" %}

{% block content %}
  
<h1>Activation link was sent to your mailbox!</h1>

{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                {{ form.username|as_crispy_field }}
            </div>
            <div class="col">
                {{ form.password|as_crispy_field }}
            </div>    
        </div>
        <button type="submit" class="btn btn-success">Login</button>
    </form>

{% endblock %}

templates/accounts/password_change_done.html
{% extends "base.html" %}

{% block content %}
  
<h2>Password changed.</h2>
<a href="{% url 'tasks:tasks' %}", class="btn btn-primary", role="button">Go To Main Page</a>

{% endblock %}

templates/accounts/password_change_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                {{ form.old_password|as_crispy_field }}
            </div>
        </div>

        <div class="row">
            <div class="col">
                {{ form.new_password1|as_crispy_field }}
            </div>
            <div class="col">
                {{ form.new_password2|as_crispy_field }}
            </div>
        </div>

        <button type="submit" class="btn btn-success">Change Password</button>
    </form>

{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                {{ form.email|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.password1|as_crispy_field }}
            </div>
            <div class="col">
                {{ form.password2|as_crispy_field }}
            </div>
        </div>

        <button type="submit" class="btn btn-success">Sign Up</button>
    </form>

{% endblock %}