apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change_form.html", success_url=reverse_lazy('accounts:password_change_done')), name='change_password'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"), name='password_change_done'),
    path('account-activation-sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('account-activated/', views.account_activated, name='account_activated'),
    path('account-activation-failed/', views.activation_failed, name='account_activation_failed')
]

apps/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.TasksListView.as_view(), name='tasks'),
    path('<uuid:pk>/', views.TaskDetailView.as_view(), name='task'),
    path('add-task/', views.TaskCreateView.as_view(), name='add_task'),
    path('<uuid:pk>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('<uuid:pk>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
    path('send-reminders/', views.send_reminders, name='send_reminders')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('', include('apps.tasks.urls'))
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>Title</title>
  </head>
  <body>
        
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        <ul class="navbar-nav">
          
          {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
          </li>

          {% else %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:tasks' %}">Tasks</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:add_task' %}">Add Task</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'tasks:send_reminders' %}">Send reminders</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ request.user.username }}
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
            </div>
          </li>
          
          {% endif %}
        </ul>
    </nav>

    <div class="content container">

      {% block content %}
      {% endblock %}

    </div>

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    
  </body>
</html>