apps/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.TasksListView.as_view(), name='tasks'),
    path('<uuid:pk>/', views.TaskDetailView.as_view(), name='task'),
    path('add-task/', views.TaskCreateView.as_view(), name='add_task'),
    path('<uuid:pk>/update/', views.TaskUpdateView.as_view(), name='update_task'),
    path('<uuid:pk>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
    path('send-reminders/', views.send_reminders, name='send_reminders')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('', include('apps.tasks.urls'))
]

apps/tasks/models.py
from django.db import models
from apps.core.models import Timestamp
from apps.accounts.models import User
import uuid
from datetime import datetime, timedelta


class Task(Timestamp):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=500, blank=True)
    date = models.DateTimeField()
    sent_reminder = models.BooleanField(default=False)
    remind_at = models.DateTimeField(null=True)

    def __str__(self):
        return (self.title)

    def set_default_remind_time(self):
        return self.date - timedelta(hours=24)

    def save(self, *args, **kwargs):
        if self.remind_at is None:
            self.remind_at = self.set_default_remind_time()
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['date']

apps/tasks/forms.py
from django import forms
from .models import Task


class TaskCreateForm(forms.ModelForm):
    date = forms.DateTimeField(
        input_formats = ['%Y-%m-%dT%H:%M'], 
        widget = forms.DateTimeInput(
        attrs={
            'type': 'datetime-local',
            'class': 'form-control'
            },
        format='%Y-%m-%dT%H:%M')
        )
    remind_at = forms.DateTimeField(
        required=False,
        input_formats = ['%Y-%m-%dT%H:%M'], 
        widget = forms.DateTimeInput(
        attrs={
            'type': 'datetime-local',
            'class': 'form-control'
            },
        format='%Y-%m-%dT%H:%M')
        )
    class Meta:
        model = Task
        fields = [
            'title',
            'description',
            'date',
            'remind_at'
        ]
        

apps/tasks/views.py
from django.views import generic
from django.shortcuts import reverse, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import render_to_string
from datetime import timedelta, datetime

from .models import Task
from .forms import TaskCreateForm


class TasksListView(LoginRequiredMixin, generic.ListView):

    model = Task
    context_object_name = 'tasks'
    template_name = 'tasks/list.html'

    def get_queryset(self):
        user = self.request.user
        tasks = Task.objects.filter(user=user)
        return tasks
    

class TaskDetailView(generic.DetailView):

    model = Task
    context_object_name = 'task'
    template_name = 'tasks/detail.html'
    

class TaskCreateView(generic.edit.CreateView):

    model = Task
    form_class = TaskCreateForm
    template_name = 'tasks/create.html'

    def form_valid(self, form):
        user = self.request.user

        if user.is_verified:
            form.instance.user = user
            return super().form_valid(form)

    def get_success_url(self):
        return reverse('tasks:tasks')


class TaskUpdateView(generic.edit.UpdateView):
    
    model = Task
    form_class = TaskCreateForm
    template_name = 'tasks/update.html'

    def get_success_url(self):
        return reverse('tasks:task', kwargs={"pk": self.object.id})


class TaskDeleteView(generic.edit.DeleteView):
    
    model = Task
    template_name = 'tasks/delete.html'

    def get_success_url(self):
        return reverse('tasks:tasks')

# reminders email is sent when it's less than 24 hours to the task's date
def send_reminders(request):
    tasks = Task.objects.all()
    time_now = datetime.now()

    for task in tasks:

        if (task.date < datetime.now() + timedelta(hours=24) 
            and task.sent_reminder == False):
            
            subject = task.title
            message = render_to_string('tasks/reminder_email.html',
                {
                'date': task.date,
                'description': task.description,
            })
            from_email = 'tasks@reminders.com'
            task.user.email_user(subject, message, from_email)
            task.sent_reminder = True
            task.save()

    return redirect('/')

templates/tasks/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  
<form method="POST">
    {% csrf_token %}
    
    {{form.title|as_crispy_field}}
    {{form.description|as_crispy_field}}

    {{form.date|as_crispy_field}}
    <div class="form-group">
        <input type="checkbox" name="" id="custom-date-reminder" onclick="custom_date()">
        <label for="custom-date-reminder" id="custom-date-reminder">
            Select to set custom remind time.
            Otherwise reminder will be sent 24 hours before tasks date.
        </label>
    </div>

    <div hidden=true id="remind-date">
        {{form.remind_at|as_crispy_field}}
    </div>

    <button class="btn btn-success" type="submit">Add</button>
    <a href="{{request.META.HTTP_REFERER}}" role="button" class="btn btn-primary">Back</a>
</form>

<script>
    function custom_date() {
        var x = document.getElementById("remind-date");
        if (x.hidden === true) {
            x.hidden = false;
        } 
        else {
            x.hidden = true;
        }
    }
</script>

<style>
    #custom-date-reminder {
        color: orange;
    }
</style>
{% endblock content %}

templates/tasks/delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  
<form method="POST">
    {% csrf_token %}
    <p>Are you sure?</p>
    <button class="btn btn-danger" type="submit">Delete</button>
    <a href="{{request.META.HTTP_REFERER}}" role="button" class="btn btn-primary">Back</a>
</form>


{% endblock content %}

templates/tasks/detail.html
{% extends "base.html" %}

{% block content %}

<div class='col-12'>

    <strong>{{task.title}}</strong>
    <p>{{task.date}}</p>
    <p>{{task.description}}</p>

    <a href="{{request.META.HTTP_REFERER}}" role="button" class="btn btn-primary">Back</a>

</div>

{% endblock content %}

templates/tasks/list.html
{% extends 'base.html' %}

{% block content %}

<ul class="list-group list-group">
{% for task in tasks %}

    <a 
    href="{% url 'tasks:task' task.pk %}" 
    class="list-group-item list-group-item-action">

    {{task.date}} {{task.title}}  send reminder at {{task.remind_at}}

    <object>
        <a href="{% url 'tasks:delete_task' task.pk %}" role="button" class="btn btn-warning float-right">
            Delete
        </a>
        <a href="{% url 'tasks:update_task' task.pk %}" role="button" class="btn btn-secondary float-right mr-3">
            Update
        </a>
    </object>

    
    </a>

{% endfor %}
</ul>

{% endblock content %}

templates/tasks/reminder_email.html
{% autoescape off %}
Hi,

You have a task to do at {{date}}.

{% if description %}
Description:
{{description}}
{% endif %}

EEP EEP
{% endautoescape %}

templates/tasks/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    
    <button class="btn btn-success" type="submit">Update</button>
    <a href="{{request.META.HTTP_REFERER}}" role="button" class="btn btn-primary">Back</a>
</form>


{% endblock content %}